name: DicePlugin
version: 0.2
author: Highfire1
main: highfire1.diceplugin.diceplugin.Diceplugin
website: https://github.com/Highfire1/diceplugin
api-version: 1.17
commands:
  roll:
    description: Rolls a dice
    usage: /roll xdx
    aliases: [r]
